@startuml
actor User
participant ":UI" as UI
participant ":AddCommand" as AddCommand
participant ":IngredientStorage" as IngredientStorage
participant ":Storage" as Storage
participant ":Ingredient" as Ingredient

User -> UI: "add -ingredient=tomato -quantity=5 -expiry=2025/04/03"
activate UI
UI -> AddCommand: addIngredient("-ingredient=tomato -quantity=5 -expiry=2025/04/03")
activate AddCommand
AddCommand -> Ingredient: new Ingredient(ID, tomato, 5, 2025/04/03)
activate Ingredient
Ingredient --> AddCommand
deactivate Ingredient
AddCommand -> IngredientStorage: addToStorage(ingredient)
activate IngredientStorage
IngredientStorage -> Storage: storeData()
activate Storage
Storage -> Storage: Save to file
Storage --> IngredientStorage
deactivate Storage
IngredientStorage --> AddCommand
deactivate IngredientStorage
AddCommand -->> UI
deactivate AddCommand
UI -->> User
deactivate UI
@enduml