@startuml
hide circle
skinparam classAttributeIconSize 0

class Recipe {
    - String recipeName
    - ArrayList<Ingredient> ingredients
    - ArrayList<String> tags

    + Recipe(String recipeName)
    + Recipe(String recipeName, ArrayList<Ingredient> ingredients)
    + getRecipeName(): String
    + setRecipeName(String recipeName)
    + getIngredients(): ArrayList<Ingredient>
    + setIngredients(ArrayList<Ingredient> ingredients)
    + getTags(): ArrayList<String>
    + setTags(ArrayList<String> tags)
    + getName(): String
    + toString(): String
}

class RecipeBank {
    - ArrayList<Recipe> recipeBank

    + initializeRecipeBank(List<Recipe> recipesList)
    + addRecipeToRecipeBank(Recipe recipe)
    + getRecipeBank(): ArrayList<Recipe>
    + getRecipeBankSize(): Integer
    + removeRecipeFromRecipeBank(String command)
    + contains(String recipeName): boolean
    + getRecipeByName(String recipeName): List<Recipe>
    + getRecipeByORTags(ArrayList<String> tags): ArrayList<Recipe>
    + getRecipeByANDTags(ArrayList<String> tags): ArrayList<Recipe>
    + promptUserForRecipeDish(List<Recipe> recipes): Recipe
    + getIngredientList(Dish dish): List<Ingredient>
    + clear()
}

RecipeBank "1" *-- "*" Recipe : contains
Recipe -* "1..*" Ingredient : has
RecipeBank - Dish : references

@enduml
