@startuml

hide circle
skinparam classAttributeIconSize 0

class Parser {
    - String NEW_INGREDIENTS_FLAG
    - String NEW_NAME_FLAG
    - String RECIPE_FLAG
    + decipherCommand(receivedText: String): void
    + void handleAddCommand(receivedText: String): void
    + void handleDeleteCommand(receivedText: String): void
    + void handleSearchCommand(receivedText: String): void
    + String parseTagsForSearch(receivedText: String): String
    + String parseSearchType(receivedText: String): String
    ...
}

class ListCommand {
    - String COMMAND_WORD
    + void displayRecipeBank(): void
    + void displayDishList(receivedText: String): void
    + void displayIngredients(): void
    ...
}

class AddCommand {
    - String COMMAND_WORD
    + void addDish(receivedText: String): void
    + void addRecipe(receivedText: String): void
    + void addIngredient(receivedText: String): void
    ...
}

class DeleteCommand {
    - String COMMAND_WORD
    + void deleteDish(receivedText: String): void
    + void deleteIngredient(receivedText: String): void
    + void deleteRecipe(receivedText: String): void
    ...
}

class UpdateCommand {
    - String COMMAND_WORD
    + void updateDish(receivedText: String): void
    + void updateRecipe(receivedText: String): void
    + void updateIngredient(receivedText: String): void
    ...
}

class ViewCommand {
    - String COMMAND_WORD
    + void displayShoppingList(): void
    + void displayDishMonth(month: int, year: int): void
    + void displayDishMonth(month: int): void
    ...
}

class HelpCommand {
    - String COMMAND_WORD
    + void showHelp(): void
    ...
}

class SuggestCommand {
    - String COMMAND_WORD
    + void printSuggestions(): void
    ...
}

class SearchCommand {
    - String COMMAND_WORD
    + void printSearchResult(tags: String, searchType: String): void
    ...
}

Parser "1" .up.> HelpCommand : "uses"
Parser "1" .up.> UpdateCommand : "uses"
Parser "1" .up.> AddCommand : "uses"
DeleteCommand <. "1" Parser : "uses"
Parser "1" ..> ListCommand : "uses"
Parser "1" .> SuggestCommand : "uses"
Parser "1" ..> SearchCommand : "uses"
Parser "1" ..> ViewCommand : "uses"


@enduml
