@startuml

hide circle
skinparam classAttributeIconSize 0

class Parser {
    - NEW_INGREDIENTS_FLAG : String
    - NEW_NAME_FLAG : String
    - RECIPE_FLAG : String
    + decipherCommand(receivedText: String)
    + handleAddCommand(receivedText: String)
    + handleDeleteCommand(receivedText: String)
    + handleSearchCommand(receivedText: String)
    + parseTagsForSearch(receivedText: String): String
    + parseSearchType(receivedText: String): String
    ...
}

class ListCommand {
    - COMMAND_WORD : String
    + displayRecipeBank()
    + displayDishList(receivedText: String)
    + displayIngredients()
    ...
}

class AddCommand {
    - COMMAND_WORD : String
    + addDish(receivedText: String)
    + addRecipe(receivedText: String)
    + addIngredient(receivedText: String)
    ...
}

class DeleteCommand {
    - COMMAND_WORD : String
    + deleteDish(receivedText: String)
    + deleteIngredient(receivedText: String)
    + deleteRecipe(receivedText: String)
    ...
}

class UpdateCommand {
    - COMMAND_WORD : String
    + updateDish(receivedText: String)
    + updateRecipe(receivedText: String)
    + updateIngredient(receivedText: String)
    ...
}

class ViewCommand {
    - COMMAND_WORD : String
    + displayShoppingList()
    + displayDishMonth(month: int, year: int)
    + displayDishMonth(month: int)
    ...
}

class HelpCommand {
    - COMMAND_WORD : String
    + showHelp()
    ...
}

class SuggestCommand {
    - COMMAND_WORD : String
    + printSuggestions()
    ...
}

class SearchCommand {
    - COMMAND_WORD : String
    + printSearchResult(tags: String, searchType: String)
    ...
}

Parser "1" .up.> HelpCommand : "uses"
Parser "1" .up.> UpdateCommand : "uses"
Parser "1" .up.> AddCommand : "uses"
DeleteCommand <. "1" Parser : "uses"
Parser "1" ..> ListCommand : "uses"
Parser "1" .> SuggestCommand : "uses"
Parser "1" ..> SearchCommand : "uses"
Parser "1" ..> ViewCommand : "uses"


@enduml
