@startuml

hide circle
skinparam classAttributeIconSize 0

class CalendarPrinter {
    + BLANK_SPACE: String
    + printMonthCalendar(year: int, month: Month, list: ArrayList<Dish>)
    - printCalendarRow(year: int, month: Month, startDate: int, daysInMonth: int, list: ArrayList<Dish>)
    - printFoodRows(year: int, month: Month, startDate: int, daysInMonth: int, list: ArrayList<Dish>)
    - printFirstCalendarRow(year: int, month: Month, list: ArrayList<Dish>, firstDayOfWeek: int, today: LocalDate)
    - printFirstFoodRows(year: int, month: Month, list: ArrayList<Dish>, firstDayOfWeek: int)
}


class Ui {
    + DISPLAYED_INDEX_OFFSET: int
    + LINE_DIVIDER: String
    + WELCOME_MESSAGE: String
    + ASCII_MESSAGE: String
    + MESSAGE_INDEXED_LIST_ITEM: String
    + printLineDivider()
    + showWelcomeMessage()
    + printItems(messages: String...)
    + printDishListView(dishes: List<Dish>)
    + printShoppingListView(shoppingList: ArrayList<Ingredient>)
    + printRecipeListView(recipes: ArrayList<Recipe>)
    + printIngredientListView(ingredients: HashMap<String, List<Ingredient>>)
    - formatIngredientsForList(ingredient: Ingredient)
    - printAsIndexedList(list: List<String>)
    - getIndexedListForViewing(listItems: List<String>) : String
    - getIndexedListItem(visibleIndex: int, listItem: String) : String
    + waitForCommand()
}
@enduml

